### ISSUE TITLE
Isn't an issue, but I didn't know where to put this question - What is the ZSH theme shown in the screenshots in this repo?

### ISSUE THREAD

**Issue by ghost** [embark-theme/kitty#2]

**Comment by skbolton** [comment]
I am using [starship](https://starship.rs/) with some nerdfonts instead of the standard unicode chars. [Here]( https://github.com/skbolton/titan/blob/master/starship/starship.toml) is the starship config from my dots.

**Comment by skbolton** [comment]
@hydroplum let me know if you have any other questions

**Comment by ghost** [comment]
@skbolton Thanks for the theme link! Really appreciate it
